name: Add new lineages

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0/5 * * * *"

jobs:
  update_lineages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Installing Requirements
        run: pip install -r requirements.txt
      - run: python main.py
      - name: Auto-commit
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Update Lineages
            commit_options: "--no-verify"
